version: '3'

services:
    eureka:
        image: 'eurekaserver.jar:latest'
        container_name: Eureka
        hostname: eurekahostname
        build:
          context: .
        ports:
            - 8761:8761
    
    zuul:
        image: 'zuulapigateway.jar:latest'
        container_name: Zuul
        hostname: zuulhostname
        build:
          context: .
        ports:
            - 8080:8080
            
    authentication:
        image: 'authenticationms.jar:latest'
        container_name: Authentication
        hostname: authenticationhostname
        environment:
             - DB_SERVER=postgres
             - POSTGRES_PASSWORD=pie
             - POSTGRES_USER=postgres
             - POSTGRES_DB=Authenticate
             - SPRING_RABBITMQ_HOST=rabbitmq
        build:
          context: .
        ports:
            - 8081:8081
        links:
            - postgres
    
    pgadmin:
        image: dpage/pgadmin4:4.18
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: mariobove1996@gmail.com
            PGADMIN_DEFAULT_PASSWORD: admin
            PGADMIN_LISTEN_PORT: 50
      ports:
         - "5050:50"
      volumes:
         - pgadmin-data:/var/lib/pgadmin
      links:
         - "db:pgsql-server"
            
    postgres:
        image: postgres:latest
        container_name: postgres
        restart: always
        environment:
            POSTGRES_DB: Authenticate
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: pie
            PGDATA: /var/lib/postgresql/data
        volumes:
            - db-data:/var/lib/postgresql/data
        ports:
            - 5432:5432
             
    rabbitmq3:
        image: rabbitmq:3-management
        container_name: rabbitmq
        environment:
            RABBITMQ_ERLANG_COOKIE: 'secret cookie here'
        ports:
            - 5672:5672
            - 15672:15672
        
volumes:
   db-data:
   pgadmin-data:
      