version: "3.7"
services:
    authenticationDb:
        image: taas2021/db-authenticate
        container_name: authenticationDb
        hostname: authenticationDb
        restart: always
        environment:
            POSTGRES_DB: Authenticate
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: pie
            PGDATA: /var/lib/postgresql/data
        volumes:
            - authenticate-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
       
    chatDb:
        image: taas2021/db-chat
        container_name: chatDb
        hostname: chatDb
        restart: always
        environment:
            POSTGRES_DB: Chat
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: pie
            PGDATA: /var/lib/postgresql/data
        volumes:
            - chat-data:/var/lib/postgresql/data
        ports:
            - "5433:5432"
            
    courseDb:
        image: taas2021/db-course
        container_name: courseDb
        hostname: courseDb
        restart: always
        environment:
            POSTGRES_DB: Courses
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: pie
            PGDATA: /var/lib/postgresql/data
        volumes:
            - course-data:/var/lib/postgresql/data
        ports:
            - "5434:5432"
            
    calendarDb:
        image: taas2021/db-calendar
        container_name: calendarDb
        hostname: calendarDb
        restart: always
        environment:
            POSTGRES_DB: Calendar
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: pie
            PGDATA: /var/lib/postgresql/data
        volumes:
            - calendar-data:/var/lib/postgresql/data
        ports:
            - "5435:5432"
 
    pgadmin:
        image: taas2021/pg-admin
        container_name: pgadmin
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: mariobove1996@gmail.com
            PGADMIN_DEFAULT_PASSWORD: admin
            PGADMIN_LISTEN_PORT: 50
        ports:
            - "5050:50"
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        links:
            - "chatDb:serverChat"
            - "authenticationDb:serverAuthenticate"
            - "courseDb:serverCourses"
            - "calendarDb:serverCalendar"
            
    rabbitmq3:
        image: taas2021/rabbitmq
        container_name: rabbitmq
        environment:
            RABBITMQ_ERLANG_COOKIE: 'secret cookie here'
        ports:
            - 5672:5672
            - 15672:15672
       
    eureka:
        image: taas2021/eureka-microservice
        container_name: Eureka
        hostname: eurekahostname
        #build:
        #    context: ./Back-End/EurekaServer
        ports:
            - "8761:8761"
    
    zuul:
        image: taas2021/zuul-microservice
        container_name: Zuul
        #build:
        #    context: ./Back-End/ZuulApiGateway
        ports:
            - 8080:8080
        environment:
            - SPRING_APPLICATION_NAME=zuul-service

    authentication:
        image: taas2021/authentication-microservice
        container_name: AuthenticationMS
        hostname: authenticateservice
        environment:
             - DB_SERVER=authenticationDb:5432
             - POSTGRES_PASSWORD=pie
             - POSTGRES_USER=postgres
             - POSTGRES_DB=Authenticate
             - SPRING_RABBITMQ_HOST=rabbitmq
        #build:
        #  context: ./Back-End/AuthenticationMS
        ports:
            - "8081:8081"
        depends_on:
            - authenticationDb

    course:
        image: taas2021/course-microservice
        container_name: CourseMS
        hostname: courseservice
        environment:
             - DB_SERVER=courseDb:5432
             - POSTGRES_PASSWORD=pie
             - POSTGRES_USER=postgres
             - POSTGRES_DB=Courses
             - SPRING_RABBITMQ_HOST=rabbitmq
        #build:
        #  context: ./Back-End/CoursesMS
        ports:
            - "8084:8084"
        depends_on:
            - courseDb
            - eureka
            - rabbitmq3

    chat:
        image: taas2021/chat-microservice
        container_name: ChatMS
        hostname: chatservice
        environment:
             - DB_SERVER=chatDb:5432
             - POSTGRES_PASSWORD=pie
             - POSTGRES_USER=postgres
             - POSTGRES_DB=Chat
             - SPRING_RABBITMQ_HOST=rabbitmq
        #build:
        #  context: ./Back-End/ChatMS
        ports:
            - "8083:8083"
        depends_on:
            - chatDb
            - eureka
            - rabbitmq3
            
    calendar:
        image: taas2021/calendar-microservice
        container_name: CalendarMS
        hostname: calendarservice
        environment:
             - DB_SERVER=calendarDb:5432
             - POSTGRES_PASSWORD=pie
             - POSTGRES_USER=postgres
             - POSTGRES_DB=Calendar
             - SPRING_RABBITMQ_HOST=rabbitmq
        #build:
        #  context: ./Back-End/CalendarMS
        ports:
            - "8082:8082"
        depends_on:
            - calendarDb
            - eureka
            - rabbitmq3
           
volumes:
   authenticate-data:
   chat-data:
   course-data:
   calendar-data:
   pgadmin-data:
