apiVersion: v1
kind: Service
metadata:
  name: authentication
spec:
  selector:
    app: authentication
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 8081
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      labels:
        app: authentication
    spec:
      containers:
        - name: authentication
          image: taas2021/authentication-microservice:latest
          envFrom:
            - configMapRef:
                name: authentication-config
          ports:
            - containerPort: 8081
          imagePullPolicy: Always
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authentication-config
data:
     DB_SERVER: authenticate-db
     POSTGRES_PASSWORD: pie
     POSTGRES_USER: postgres
     POSTGRES_DB: Authenticate
     SPRING_RABBITMQ_HOST: rabbitmq