apiVersion: v1
kind: Service
metadata:
  name: chat
spec:
  selector:
    app: chat
  ports:
    - port: 8083
      targetPort: 8083
      nodePort: 8083
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
        - name: chat
          image: taas2021/chat-microservice-kube:latest
          envFrom:
            - configMapRef:
                name: chat-config
          ports:
            - containerPort: 8083
          imagePullPolicy: Always
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-config
data:
     DB_SERVER: chat-db:5433
     POSTGRES_PASSWORD: pie
     POSTGRES_USER: postgres
     POSTGRES_DB: Chat
     SPRING_RABBITMQ_HOST: rabbitmq