apiVersion: v1
kind: Service
metadata:
  name: courses
spec:
  selector:
    app: courses
  ports:
    - port: 8084
      targetPort: 8084
      nodePort: 8084
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: courses
spec:
  replicas: 1
  selector:
    matchLabels:
      app: courses
  template:
    metadata:
      labels:
        app: courses
    spec:
      containers:
        - name: courses
          image: taas2021/course-microservice-kube:latest
          envFrom:
            - configMapRef:
                name: courses-config
          ports:
            - containerPort: 8084
          imagePullPolicy: Always
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: courses-config
data:
     DB_SERVER: courses-db:5434
     POSTGRES_PASSWORD: pie
     POSTGRES_USER: postgres
     POSTGRES_DB: Courses
     SPRING_RABBITMQ_HOST: rabbitmq