apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - port: 5672
      name: client
      targetPort: 5672
      nodePort: 5672
    - port: 15672
      name: handler
      targetPort: 15672
      nodePort: 15672
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          envFrom:
            - configMapRef:
                name: rabbitmq-config
          ports:
            - containerPort: 5672
          imagePullPolicy: Always
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
data:
     RABBITMQ_ERLANG_COOKIE: secret cookie here