server:
  port: 8080
  servlet:
    context-path: /StudentOne
eureka:
  client:
    register-with-eureka: true
    service-url:
      zone1: http://eureka-microservice:8761/eureka/
      #defaultZone: http://eurekahostname:8761/eureka/
    prefer-same-zone-eureka: true
    region: region1
    availability-zones:
      region1: zone1
  instance:
    prefer-ip-address: true
    metadata-map:
      zone: zone1
    hostname: zuul

  eureka:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

zuul:
  sensitive-headers:

spring:
  application:
    name: zuulservice

ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false


