server:
  port: 8080
  servlet:
    context-path: /StudentOne
eureka:
  instance:
    preferIpAddress: true
    metadata-map:
      zone: zone1
    hostname: zuulhostname
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      zone1: http://eurekahostname:8761/eureka/
    prefer-same-zone-eureka: true
    region: region1
    availability-zones:
      region1: zone1

 eureka:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

zuul:
  sensitive-headers:
<<<<<<< HEAD
  routes:
    authenticationservice:
      path: /authenticationservice/**
      url: http://authenticationhostname:8081

spring:
    application:
      name: ZUULSERVICE
=======
>>>>>>> 416beaedabc5959dc06b25d99621d29fe8dc5b12

ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000

