server:
  port: 8080
  servlet:
    context-path: /StudentOne
zuul:
  routes:
    authentication:
      sensitiveHeaders:
      url: http://localhost:8081/StudentOne
    calendar:
      sensitiveHeaders:
      url: http://localhost:8082/StudentOne

