server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  #server:
  #  waitTimeInMsWhenSyncEmpty: 5
  serviceUrl:
    defaultZone: http://eurekahostname:8761/eureka/

  instance:
    hostname: eurekahostname



logging:
  level:
    com.netflix: DEBUG
    org.springframework.web: DEBUG
    com.gruppo13: DEBUG

